quarkus:
  application:
    name: culinary-answer

  devservices:
    enabled: false

#  micrometer:
#    export:
#      otlp:
#        publish: true
#        default-registry: true
#        url: ${OTEL_COLLECTOR_URL:http://localhost}:4318/v1/metrics

  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}/realms/culinary-answer
    client-id: ${KEYCLOAK_CLIENT_ID:backend-service}
    secret: ${KEYCLOAK_SECRET:secret}
  keycloak:
    admin-client:
      server-url: ${KEYCLOAK_URL:http://localhost:8080}

  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    category:
      "br.dev.marco":
        level: INFO

  rest-client:
    keycloakAdmin:
      url: ${KEYCLOAK_URL:http://localhost:8080}
  http:
    port: 8081
    cors: true

#      jacoco:
#    excludes:
#      - "**/domain/exception/**"
#      - "br.dev.marco.handler/*"
#      - "**/infra/repository/entity/*"
#      - "**/infra/security/exceptions/*"
#      - "**/infra/security/request/*"
#      - "**/infra/web/request/*"
#      - "**/infra/web/response/*"
#      - "**/mapper/*Impl.class"
#      - "**/usecase/enuns/*"
#      - "**/usecase/exceptions/*"

secrets:
  openAi: ${quarkus.profile}/open-ai/secrets
  keycloak: ${quarkus.profile}/keycloak/secrets

"%dev":
  quarkus:
    secretsmanager:
      endpoint-override: http://localstack:4566
      aws:
        region: us-east-1
        credentials:
          type: static
          static-provider:
            access-key-id: teste
            secret-access-key: teste
    dynamodb:
      endpoint-override: http://localstack:4566
      aws:
        region: us-east-1
        credentials:
          type: static
          static-provider:
            access-key-id: teste
            secret-access-key: teste

