quarkus:
  application:
    name: culinary-answer

  devservices:
    enabled: false

  micrometer:
    export:
      otlp:
        publish: true
        default-registry: true
        url: ${OTEL_COLLECTOR_URL:http://localhost}:4318/v1/metrics

  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost}:8180/realms/culinary-answer
    client-id: ${KEYCLOAK_CLIENT_ID:backend-service}
    secret: ${KEYCLOAK_SECRET:secret}
  keycloak:
    admin-client:
      server-url: ${KEYCLOAK_URL:http://localhost}:8180

  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
    category:
      "br.dev.marco":
        level: INFO

#Injetar TOKEN através do SecretsManager
secret:
  API_TOKEN: "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"

